export * as AuthControllers from './AuthControllers.js'
export * as DormitoryPrice from './DormitoryPrice.js'
export * as MailerControllers from './MailerControllers.js'
export * as PageControllers from './PageControllers.js'
export * as PostControllers from './PostControllers.js'
export * as SpecialtiesControllers from './SpecialtiesControllers.js'
